{
  "openapi": "3.0.1",
  "info": {
    "version": "1.0.0",
    "title": "Swagger test",
    "description": "Showing off swagger-ui-express",
    "license": {
      "name": "MIT",
      "url": "https://opensource.org/licenses/MIT"
    }
  },
  "consumes": ["application/json", "multipart/form-data"],
  "produces": ["application/json", "multipart/form-data"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://final-group-project-node.herokuapp.com" }
  ],
  "tags": [
    {
      "name": "Auth",
      "description": "Authorization endpoints"
    },
    {
      "name": "User",
      "description": "User endpoints"
    }
  ],
  "paths": {
    "/auth/register": {
      "post": {
        "tags": ["Auth"],
        "summary": "User registration",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "409": {
            "description": "Provided email already exists",
            "content": {}
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "tags": ["Auth"],
        "summary": "User login",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Login's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "401": {
            "description": "UNAUTHORIZED",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      }
    },
    "/auth/logout": {
      "post": {
        "tags": ["Auth"],
        "summary": "User logout , send none content!",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "Successful logout 204 No content",
            "content": {}
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "403": {
            "description": "FORBIDDEN",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      }
    },
    "/users/current": {
      "get": {
        "tags": ["User"],
        "summary": "User pull information about current user!",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {},
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentGetResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "403": {
            "description": "FORBIDDEN",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      },
      "patch": {
        "tags": ["User"],
        "summary": "Update user's information!",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CurrentPatchRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentPatchResponse"
                }
              }
            }
          },
          "400": {
            "description": "Bad request (invalid request body)",
            "content": {}
          },
          "403": {
            "description": "FORBIDDEN",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      }
    },
    "/users/verify": {
      "get": {
        "tags": ["User"],
        "summary": "Verification for user!",
        "parameters": [{ "in": "path", "name": "verificationToken" }],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentGetVerification"
                }
              }
            }
          },
          "400": {
            "description": "Your verification token is not valid",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      }
    },
    "/users/avatars": {
      "patch": {
        "tags": ["User"],
        "summary": "Update avatar across cloudinary!",
        "parameters": {},
        "security": [{ "Bearer": [] }],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/AvatarRequest"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful operation",
            "content": {
              "multipart/form-data": {
                "schema": {
                  "$ref": "#/components/schemas/AvatarResponse"
                }
              }
            }
          },
          "400": {
            "description": "Your verification token is not valid",
            "content": {}
          },
          "403": {
            "description": "FORBIDDEN",
            "content": {}
          },
          "500": {
            "description": "INTERNAL_SERVER_ERROR"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        },
        "example": { "email": "qwe@qwe.com", "password": "qwe123" }
      },
      "RegistrationResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "password": {
              "type": "number",
              "description": "User's password",
              "example": "qwe123"
            }
          }
        },
        "example": { "email": "qwe@gmail.com", "password": "qwe123" }
      },
      "LoginRequest": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "password": {
              "type": "number",
              "description": "User's password"
            }
          }
        },
        "example": {
          "email": "grisha1996111616@gmail.com",
          "password": "Pheonix"
        }
      },
      "LoginResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "password": {
              "type": "number",
              "description": "User's password"
            }
          }
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNjljY2VjMjA2NTU2Mjk3ODY1MDdlYSIsImlhdCI6MTYxNzczMjQxNCwiZXhwIjoxNjE3ODE4ODE0fQ.HZJ5ee1NazSeARNFQrJzLlMkzkjXkpWwbKCumURUVgs",
            "user": {
              "name": "Shara",
              "email": "grisha1996111616@gmail.com",
              "avatarURL": "https://res.cloudinary.com/drk4jlehk/image/upload/v1617561654/Photo/m8st0gyjbospqglbyuaa.png"
            }
          }
        }
      },
      "CurrentGetResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {}
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "user": {
              "name": "qgrl",
              "email": "grisha1996111616@gmail.com",
              "avatarURL": "https://res.cloudinary.com/drk4jlehk/image/upload/v1617561654/Photo/m8st0gyjbospqglbyuaa.png"
            }
          }
        }
      },
      "CurrentPatchResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {}
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "user": {
              "name": "updatedNmae",
              "email": "grisha1996111616@gmail.com"
            }
          }
        }
      },
      "CurrentPatchRequest": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "description": "User's name",
              "format": "string"
            }
          }
        },
        "example": { "name": "Heroku" }
      },
      "CurrentGetVerification": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {}
        },
        "example": {
          "status": "success",
          "code": "200",
          "message": "Verification successful!"
        }
      },
      "AvatarRequest": {
        "type": "object",
        "properties": {
          "avatar": {
            "type": "string"
          },
          "fileName": {
            "type": "string",
            "format": "binary"
          }
        }
      },
      "AvatarResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {}
        },
        "example": {
          "status": "success",
          "code": 200,
          "data": {
            "avatarUrl": "https://res.cloudinary.com/drk4jlehk/image/upload/v1617737101/Photo/wkdcar88bft1djvwfdt7.png"
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
